### ISSUE TITLE
Returns TypeError: options.tags.split is not a function

### ISSUE THREAD

**Issue by srdno** [big-skim-milk/sk-hashtagger#1]
Not much else

**Comment by big-skim-milk** [comment]
I think you might have your tags stored in the collection as an array. The upcoming version will be a bit more lenient, but until then you can do something like this:

`let tags = $w('#dynamicDataset').getCurrentItem().tags.join(', ');`

> Either the above or below

`let tags = Array.from($w('#dynamicDataset').getCurrentItem().tags).join(', ');`

and then in options, set `tags: tags, delimiter: ', ',`

**Comment by srdno** [comment]
Thank you, it works :)
